### ISSUE TITLE
Add more meta functionality than just an @id

### ISSUE THREAD

**Issue by burodepeper** [burodepeper/language-ass#5]
- [ ] the `@123` is practical as a search anchor; **this behaviour should remain**
- [ ] additional functionality:
  - [ ] skip/status (append a reason? FAILS, TODO)
  - [ ] default-domain (add .md to every scope, for instance)
  - [ ] ignore-leading-whitespace
  - [ ] comment (removes the special status of the # character)
  - [ ] meta functions are _global_ by default, and can be changed per test
  - [ ] offset (specify partial output)
